### ISSUE TITLE
OPENCMISS_VERSION problem

### ISSUE THREAD

**Issue by chrispbradley** [OpenCMISS/setup#12]
If you have OPENCMISS_PERFORM_INITIAL_BUILD set to False then OPENCMISS_VERSION is not set. This then causes the following around line 175

if (NOT OPENCMISS_VERSION IN_LIST KNOWN_OPENCMISS_VERSIONS)
    set(VALID_CONFIG FALSE)
    list(APPEND ERROR_MSG "${OPENCMISS_VERSION} is not a known OpenCMISS version.")
endif ()

to fail. If OPENCMISS_PERFORM_INITIAL_BUILD then this line is executed

    set(OPENCMISS_VERSION "develop" CACHE STRING "The branch or tag to setup.  Must be one of: ${KNOWN_OPENCMISS_VERSIONS}")

which sets OPENCMISS_VERSION. If not then 

    unset(OPENCMISS_VERSION CACHE)

is executed. If OPENCMISS_VERSION is required then it should be set for OPENCMISS_PERFORM_INITIAL_BUILD=False or the test on OPENCMISS_VERSION should be moved it an IF block.

**Comment by hsorby** [comment]
The configuration validity check should definitely be moved to an if block to fix this issue.
